package config;

public enum ConfigIdentifier {
    IP,
    Port,
    CHANGE_COLOR_OF_TEACHER,
    CHANGE_COLOR_OF_STUDENT,
    getStudentLogin ,
    getTeacherLogin ,
    getLastNameHelpTeacherFromId ,
    getLastNameHelpTeacherFromLastName ,
    getAllStudents ,
    getAllTeachers ,
    getAllCourses ,
    ShowTemperoryScoresForEA ,
    CopyLinkedListCourse_TemperoryScoresForEA ,
    ShowCoursesWithFilterForNameCourse_TemperoryScoresForEA ,
    ShowCoursesWithFilterForTeacherName_TemperoryScoresForEA ,
    ShowCourses ,
    ShowTeachers ,
    GiveCoursesFromAStudent ,
    GiveCoursesFromATeacher ,
    returnAllHelpTeachersFromACollege ,
    CanSignUpForDuplicateUsername ,
    addStudent ,
    addTeacher ,
    addCourse ,
    FindTeacher ,
    FindTeacherLastNameFromId ,
    FindTeacherFirstNameFromId ,
    FindTeacherCollegeFromId ,
    isValidTeacher ,
    FindCourse ,
    FindACourseFormACollege ,
    AddNewCourseToTeacher ,
    StringToTeacher ,
    SearchStudentByStudentNumberAndName ,
    getTeacherOfACourse ,
    GiveCoursesOfATeacher ,
    GiveCoursesOfACollege ,
    GiveStudentsOfACoursesFromId ,
    GiveStudentsOfACoursesFromString,
    FindStudentFromId ,
    FindIndexCourseFormAStudentFromCourseName ,
    RemoveCourseFromATeachersAndStudents ,
    ShowableCoursesOfStudentTemporaryScores ,
    FindIndexCourseFormAStudentFromId ,
    GetScore ,
    FindStudentsWantsToReject ,
    FindStudentsWantsToMinor ,
    RemoveStudent ,
    ShowPastCoursesForAStudent ,
    ShowStudentsForATeacherEA ,
    getStatusACourseFromAStudent ,
    getScoreACourseFromAStudent ,
    getPassesCourseFromAStudent ,
    FindStudentsWantsToRecome ,
    getIndexRequest ,
    getWeighOfCoursesPass ,
    getNumPassForACourse ,
    AddAndRemoveACourseFormTeachers ,
    RemoveACourseFormTeachers ,
    changePasswordForAStudent ,
    changePasswordAForTeacher ,
    changeLastLoginStudent ,
    changeLastLoginTeacher ,
    changeEducationStatusOfAStudent ,
    changeProtestForAStudent ,
    editEmailForAStudent ,
    editPhoneForAStudent ,
    setImageAddressOfAStudent ,
    addIdTeacherToStudentForRecome ,
    changeRecomeForStudentBecauseShowed ,
    changeRecomeForStudentBecauseShowedWithIdTeacherShouldAddToAccepted ,
    setMinorCollegeForAStudent ,
    setDormRequestForAStudent ,
    changeMinorForStudentBecauseShowedAndRejected ,
    submitRecomeForAStudent ,
    setRoomNumberForATeacher ,
    removeATeacher ,
    changeStatusTeacher ,
    editEmailForATeacher ,
    editPhoneForATeacher ,
    setImageAddressOfATeacher ,
    setAnswerAndScoreForStudent ,
    changeMinorStatusFromEA ,
    setTimesLoginForAStudent ,
    setTimesLoginForATeacher,
    getProtestForCourseStudent,
    getAnswerForCourseStudent,
    getScoreForCourseStudent,
    getMinorStatus,
    getRequestForRecommendation,
    getIdTeacherForRequest,
    getDormStatus,
    testConnection,
    getThesisDefenceFromAStudent,
    validStudentNumberForTA,
    validPublicIdForCourse,
    validDuplicatePublicIdForCourse,
    setExamDayForACourse,
    getAllCoursesFromACollege,
    sendFileToServer,
    sendFileFromServer,
    removeAFileFromServerForCw,
    addNewFileInCwForExamOrHw,
    getAllTeacherFormACollege,
    getAllCoursesFromACollegeForSelectUnit,
    saveMessagesBecauseNotConnected,
    saveMessage,
    getChatRoomsInfo,
    changeColorForMohseni,
    changeColorForAdmin,
    getMohseniLogin,
    getAdminLogin,
    ShowStudentsForMohseni,
    GiveCoursesOfAStudent,
    getFileNameOfFromUsername,
    getFileNameOfFromStudentNumber,
    getYearsToUniversityForEA,
    saveTimeForSelectionUnit,
    getLikedCourses,
    getSuggestedCourses,
    getStatusOfACourseForUnitSelection,
    addACourseToLikedCourses,
    removeACourseFromLikedCourses,
    addACourseFromCoursesWantToGetThisTerm,
    changeGroupForSelectionUnit,
    removeACourseFromCoursesWantToGetThisTerm,
    getAllStudentsFromOneCollegeAndFromOneYear,
    getAllMessagesFromAPerson,
    getAllMessagesFromTwoPersons,
    getUserNameFromName,
    getEducationalMaterialsFromACourse,
    getExamsFromACourse,
    getHomeWorksFromACourse,
    changeAnswerForHomeWorkOrExamForAStudent,
    getMessagesForAStudent,
    getMessagesForATeacher,
    removeAMessageFromAStudent,
    removeAMessageFromATeacherForMessages,
    sendMessageToEAToGetACourse,
    getTimeSelectUnitForAStudent,
    FindATeacherOrStudentForChatRoom,
    sendMessageToAPersonForRequestChatRoom,
    addStudentToCourseInCW,
    isAStudentTAOfACourse,
    getNameOfAStudentFromId,
    getStudentsNumberOfAStudentFromId,
    saveExamsOrHWsForCw,
    changeEducationalMaterialForACourse,
    getCoursesOfATeacher,
    getCoursesGroup,
    getStudentsWithFilterForMohseni,
    findStudentFromStudentNumber,
    getAllStudentForATeacherInChatRoom,
    getAllStudentForABossAndEAInChatRoom,
    finishTimeSelection,
    removeACourse,
    publicURLForServer,
    publicURLForUser,
    publicURL;

}
